[tool.poetry]
name = "coursework2"
version = "0.1.0"
description = ""
authors = ["Kira Fedotova <k.fedotova@it-park.tech>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
